/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MyListsImport } from './routes/my-lists'
import { Route as LeaderboardImport } from './routes/leaderboard'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as ChallengesImport } from './routes/challenges'
import { Route as protectedLayoutImport } from './routes/(protected)/layout'
import { Route as authLayoutImport } from './routes/(auth)/layout'
import { Route as IndexImport } from './routes/index'
import { Route as protectedProfileImport } from './routes/(protected)/profile'
import { Route as authSignInImport } from './routes/(auth)/sign-in'

// Create/Update Routes

const MyListsRoute = MyListsImport.update({
  id: '/my-lists',
  path: '/my-lists',
  getParentRoute: () => rootRoute,
} as any)

const LeaderboardRoute = LeaderboardImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const ChallengesRoute = ChallengesImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRoute,
} as any)

const protectedLayoutRoute = protectedLayoutImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRoute,
} as any)

const authLayoutRoute = authLayoutImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const protectedProfileRoute = protectedProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => protectedLayoutRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authLayoutImport
      parentRoute: typeof rootRoute
    }
    '/(protected)': {
      id: '/(protected)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedLayoutImport
      parentRoute: typeof rootRoute
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardImport
      parentRoute: typeof rootRoute
    }
    '/my-lists': {
      id: '/my-lists'
      path: '/my-lists'
      fullPath: '/my-lists'
      preLoaderRoute: typeof MyListsImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof authLayoutImport
    }
    '/(protected)/profile': {
      id: '/(protected)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof protectedProfileImport
      parentRoute: typeof protectedLayoutImport
    }
  }
}

// Create and export the route tree

interface authLayoutRouteChildren {
  authSignInRoute: typeof authSignInRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authSignInRoute: authSignInRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface protectedLayoutRouteChildren {
  protectedProfileRoute: typeof protectedProfileRoute
}

const protectedLayoutRouteChildren: protectedLayoutRouteChildren = {
  protectedProfileRoute: protectedProfileRoute,
}

const protectedLayoutRouteWithChildren = protectedLayoutRoute._addFileChildren(
  protectedLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof protectedLayoutRouteWithChildren
  '/challenges': typeof ChallengesRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-lists': typeof MyListsRoute
  '/sign-in': typeof authSignInRoute
  '/profile': typeof protectedProfileRoute
}

export interface FileRoutesByTo {
  '/': typeof protectedLayoutRouteWithChildren
  '/challenges': typeof ChallengesRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-lists': typeof MyListsRoute
  '/sign-in': typeof authSignInRoute
  '/profile': typeof protectedProfileRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(auth)': typeof authLayoutRouteWithChildren
  '/(protected)': typeof protectedLayoutRouteWithChildren
  '/challenges': typeof ChallengesRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-lists': typeof MyListsRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(protected)/profile': typeof protectedProfileRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/challenges'
    | '/dashboard'
    | '/leaderboard'
    | '/my-lists'
    | '/sign-in'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/challenges'
    | '/dashboard'
    | '/leaderboard'
    | '/my-lists'
    | '/sign-in'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(protected)'
    | '/challenges'
    | '/dashboard'
    | '/leaderboard'
    | '/my-lists'
    | '/(auth)/sign-in'
    | '/(protected)/profile'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLayoutRoute: typeof authLayoutRouteWithChildren
  protectedLayoutRoute: typeof protectedLayoutRouteWithChildren
  ChallengesRoute: typeof ChallengesRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MyListsRoute: typeof MyListsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLayoutRoute: authLayoutRouteWithChildren,
  protectedLayoutRoute: protectedLayoutRouteWithChildren,
  ChallengesRoute: ChallengesRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  MyListsRoute: MyListsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(auth)",
        "/(protected)",
        "/challenges",
        "/dashboard",
        "/leaderboard",
        "/my-lists"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(auth)": {
      "filePath": "(auth)/layout.tsx",
      "children": [
        "/(auth)/sign-in"
      ]
    },
    "/(protected)": {
      "filePath": "(protected)/layout.tsx",
      "children": [
        "/(protected)/profile"
      ]
    },
    "/challenges": {
      "filePath": "challenges.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/leaderboard": {
      "filePath": "leaderboard.tsx"
    },
    "/my-lists": {
      "filePath": "my-lists.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx",
      "parent": "/(auth)"
    },
    "/(protected)/profile": {
      "filePath": "(protected)/profile.tsx",
      "parent": "/(protected)"
    }
  }
}
ROUTE_MANIFEST_END */
